### ISSUE TITLE
博客链接挂掉了

### ISSUE THREAD

**Issue by JimChenWYU** [overtrue/blog#32]
超哥，你的博客链接404了...

**Comment by overtrue** [comment]
@JimChenWYU 哪个链接？

**Comment by JimChenWYU** [comment]
@overtrue 

![overture-blog](https://s1.ax1x.com/2018/06/19/Cz9kGQ.png)

**Comment by overtrue** [comment]
我擦，我这里正常。。。

**Comment by overtrue** [comment]
你在哪个地区，ping 一下域名看看 ip

**Comment by JimChenWYU** [comment]
@overtrue 可怕...广州，华工的校园网...

![](https://s1.ax1x.com/2018/06/19/CzP7V0.png)

**Comment by overtrue** [comment]
搞定
